apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-leitor-teste
  name: pod-leitor-teste
spec:
  serviceAccountName: pod-leitor
  containers:
  - image: alpine
    name: pod-leitor-teste
    command: ["sleep", "infinity"]