apiVersion: v1
kind: Pod
metadata:
  name: app-2
  labels:
    project: easy
spec:
  containers:
    - image: nginx
      name: nginx
      resources:
        requests:
          cpu: "0.1"
          memory: "128Mi"
        limits:
          cpu: "0.5"
          memory: "256Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  