apiVersion: v1
kind: Namespace
metadata:
  name: security
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pwpush
    component: ingress-controller
  name: pwpush
  namespace: security
spec:
  progressDeadlineSeconds: 30
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pwpush
      component: ingress-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pwpush
        component: ingress-controller
    spec:
      containers:
      - image: docker.io/pglombardo/pwpush-ephemeral
        imagePullPolicy: Always
        name: pwpush
        resources:
          requests:
            memory: "256Mi"
            cpu: 1
          limits:
            memory: "512Mi"
            cpu: 1.5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: TZ
            value: "America/Sao_Paulo"
          - name: PWP__DEFAULT_LOCALE
            value: "en"
          - name: PWP__LOG_LEVEL
            value: "warn"
          - name: PWP__LOG_TO_STDOUT
            value: 'true'
          - name: PWP__THEME
            value: "Sandstone"
          - name: PWP__BRAND__TITLE
            value: "Pwpush"
          - name: PWP__BRAND__SHOW_FOOTER_MENU
            value: 'false'
          # - name: PWP__BRAND__LIGHT_LOGO
          #   value: "http:///...."
          # - name: PWP__BRAND__DARK_LOGO
          #   value: "http:///...."
          # - name: PWP__EXPIRE_AFTER_DAYS_MIN
          #   value: ''
          # - name: PWP__EXPIRE_AFTER_DAYS_MAX
          #   value: '1'
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
