apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-sample4
spec:
  parallelism: 10
  #arguments: -o experimental-prometheus-rw --tag testid=job
  script:
    configMap:
      name: k6-test
      file: k6.js
  separate: false
  runner:
    metadata:
      labels:
        test: nginx-app
      annotations:
        environment: test
    env:
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
      - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
        value: "true"
