apiVersion: v1
kind: Pod
metadata:
  labels:
    run: debug
  name: debug
spec:
  containers:
  - image: alpine
    name: debug
    # Just spin & wait forever
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
# do ctrl + d to exit without killing the pod 
