apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: primeira-netpol
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app: redis
  ingress:
    - from:
      - podSelector: {}  # libera acesso apenas por dentro da namespace