apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-gpu
  name: nginx-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-gpu
  template:
    metadata:
      labels:
        app: nginx-gpu
    spec:
      containers:
      - image: nginx
        name: nginx-gpu
      tolerations:
      - key: "gpu"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
        