apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: platform
rules:
- apiGroups: ["", "apps"] # "" indicates the core API group and apps for deployments
  resources: ["pods", "deploments"]
  verbs: ["get", "list", "create", "delete"]
