apiVersion: v1
kind: ConfigMap
metadata:
  name: dotnet-monitor-egress
data:
  Egress__FileSystem__monitorFile__directoryPath: /diag
  Egress__AzureBlobStorage__monitorBlob__accountUri: "http://azurite:10000/devstoreaccount1"       # "https://devstoreaccount1.blob.core.windows.net"
  Egress__AzureBlobStorage__monitorBlob__containerName: "dotnet-monitor"
  Egress__AzureBlobStorage__monitorBlob__blobPrefix: "artifacts"
  Egress__AzureBlobStorage__monitorBlob__accountKey: "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
