apiVersion: v1
kind: Pod
metadata:
  labels:
    app: redis
  name: redis
  namespace: dev
spec:
  containers:
  - image: redis
    name: redis
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
      name: redis-svc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: redis
  namespace: dev
spec:
  selector:
    app.kubernetes.io/name: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: redis-svc