apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-1
    version: v2
  name: app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  strategy: {}
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: 0.25
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 5
          successThreshold: 1
        readinessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:80/
          # httpGet:
          #   path: /
          #   port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 5
          successThreshold: 2
        startupProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
